name: project-name
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - jupyter
  - jupyterlab
  - ipykernel
  - ipywidgets
  - pyprojroot
  - python-dotenv
  - pre-commit
  - nbstripout 
