[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
name = "project_name"
version = "0.0.1"
authors = [
  { name="Luuk Visser" },
]
readme = "README.md"

[tool.setuptools]
packages=["project_name"]
